# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
    - id: commitizen
    - id: commitizen-branch
    stages: [ push ]

-   repo: local
    hooks:
    -   id: add-task-id
        name: Add Task ID to commit message
        entry: python ./hooks/check_commit_msg.py
        language: python
        stages: [commit-msg]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
