name: Check branch name

on:
    pull_request:
        branches:
            - "main"

jobs:
    check_branch:
        runs-on: ubuntu-latest

        steps:
            - name: Create Github App Token
              uses: actions/create-github-app-token@v1
              id: app-token
              with:
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.APP_SECRET }}

            - name: Checkout code
              uses: actions/checkout@v4
              with:
                token: ${{ steps.app-token.outputs.token }}

            - name: Check branch name
              run: |
                  BRANCH_NAME=$(echo '${{ github.event.pull_request.head.ref }}')

                  if [[ $BRANCH_NAME == release/* || $BRANCH_NAME == hotfix/* ]]; then
                      echo "Branch name is valid"
                  else
                      echo "Branch name is invalid"
                      exit 1
                  fi
